In [240]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [241]:

x = np.ones(11)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [242]:
y = np.zeros(11)
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [243]:
add = x + y
add

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [244]:
print ("The dimension of x " , x.ndim)

The dimension of x  1


In [245]:
 print ("The shape of x " , x.shape)


The shape of x  (11,)


In [246]:
 print ("The size of x " , x.size)

The size of x  11


In [247]:
 print ("The type of x " , x.dtype)

The type of x  float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [248]:
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

In [249]:
w.ndim

2

## Q#6: Create z array contains the numbers from 1 to 3.

In [250]:
z = np.arange(1, 4)

In [251]:
z.ndim


1

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [252]:
reshapeZ= z.reshape(-1,1)
newArray = np.hstack((reshapeZ,w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [253]:
for row in newArray :
    for number in row:
        print(number)


1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [254]:
reverseArray = newArray[::-1, ::-1]  
reverseArray

array([[16, 15,  3],
       [14, 13,  2],
       [12, 11,  1]])

## Q#10: Decrement all elements of "newArray" with 1.

In [255]:
DecrementArray = newArray - 1
DecrementArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [256]:
smallest = newArray.min()  
print ("Smallest value:" , smallest)


Smallest value: 1


In [257]:
biggest = newArray.max()
print ("Biggest value:" , biggest)

Biggest value: 16


## Q#12: Print the first row of "newArray" using indexing.

In [258]:
print(newArray[0]) 


[ 1 11 12]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [259]:
print(DecrementArray[1,1]) 

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [260]:
print("number 0 : ",DecrementArray[0,0]) 

number 0 :  0


In [261]:
print("number 13 : " ,DecrementArray[1,2]) 

number 13 :  13


## Q#15: Change the shape of "newArray" to (9,1).

In [262]:
reshapenewArray = DecrementArray.reshape(9,1)
reshapenewArray

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

In [263]:
reshapenewArray.ndim

2

## Q#16: Change the shape of "newArray" to (3,2).

In [265]:
reshaped3 = newArray.flatten()[:6].reshape(3,2)
print(reshaped3)


[[ 1 11]
 [12  2]
 [13 14]]


# Well Done 🎉